name: Stop Sql Teacher Agents

on:
  workflow_dispatch:   # rulare manualÄƒ
    inputs:
      inventory_group:
        description: 'Selecteaza environmentul pe care vrei sa rulezi"'
        required: true
        type: choice
        options:
          - dev
          - prod-amihai
          - prod-itschool
        default: 'dev'

jobs:
  stop_agents:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}

      - name: Disable host key checking
        run: |
          echo "[defaults]" > ~/.ansible.cfg
          echo "host_key_checking = False" >> ~/.ansible.cfg

      - name: Stop Sql Teacher Agents
        run: |
          ansible-playbook -i ansible/inventory.ini \
          -l ${{ github.event.inputs.inventory_group }} \
          ansible/playbooks/stop_agents.yaml
